### ISSUE TITLE
Build of imediff fails with Python 3.6

### ISSUE THREAD

**Issue by eyalroz** [osamuaoki/imediff#8]
I'm using a SLES 15 distribution (SUSE Enterprise Linux Server 2015). I've downloaded imediff, and am running the `setup.py` script. After running the script,  nothing happens for a few seconds, and then I get:
````
# ./setup.py

Traceback (most recent call last):
  File "./setup.py", line 22, in <module>
    setuptools.setup()
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 495, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 114, in parse_configuration
    meta.parse()
  File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 400, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 373, in parse_section
    self[name] = value
  File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 177, in __setitem__
    value = parser(value)
  File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 466, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 323, in _parse_attr
    module = import_module(module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/imediff-2.4/src/imediff/__init__.py", line 26, in <module>
    from imediff.main import *
ModuleNotFoundError: No module named 'imediff.main'
```

**Comment by osamuaoki** [comment]
As I wrote in the updated README.md, I prefer installation via wheel.  But even if you insist on using older direct install via distutls type install, it doesn't make sense to just start ./setup.py without argument.

This is what I get issueing command like you did.
```
 $ ./setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

You may be suffering `i18n` issue.  If so,  please try:
- Remove i18n=True (or change it to i18n=False) in setup.cfg .
- Replace _ = gettext.gettext with _ = lambda x : x in src/utils.py.
- Comment out all lines containing "gettext" in the source under src/ .

setup.cfg may need more changes...

**Comment by osamuaoki** [comment]
FYI: Even after removing `python3-distutils-extra` package from my system, if you follow my updated instruction which also remove `icons=False`, you should be able to build package as a wheel package:
```
$ ./setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/imediff
copying src/imediff/diff2lib.py -> build/lib/imediff
copying src/imediff/diff3lib.py -> build/lib/imediff
copying src/imediff/utils.py -> build/lib/imediff
copying src/imediff/cli.py -> build/lib/imediff
copying src/imediff/tui.py -> build/lib/imediff
copying src/imediff/__init__.py -> build/lib/imediff
copying src/imediff/__main__.py -> build/lib/imediff
copying src/imediff/config.py -> build/lib/imediff
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/imediff
copying build/lib/imediff/diff2lib.py -> build/bdist.linux-x86_64/wheel/imediff
copying build/lib/imediff/diff3lib.py -> build/bdist.linux-x86_64/wheel/imediff
copying build/lib/imediff/utils.py -> build/bdist.linux-x86_64/wheel/imediff
copying build/lib/imediff/cli.py -> build/bdist.linux-x86_64/wheel/imediff
copying build/lib/imediff/tui.py -> build/bdist.linux-x86_64/wheel/imediff
copying build/lib/imediff/__init__.py -> build/bdist.linux-x86_64/wheel/imediff
copying build/lib/imediff/__main__.py -> build/bdist.linux-x86_64/wheel/imediff
copying build/lib/imediff/config.py -> build/bdist.linux-x86_64/wheel/imediff
running install_data
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data/data
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/share
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/share/man
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/share/man/man1
copying doc/imediff.1 -> build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/share/man/man1
copying doc/git-ime.1 -> build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/share/man/man1
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/lib
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/lib/git_core
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/lib/git_core/mergetools
copying mergetools/imediff -> build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/lib/git_core/mergetools
creating build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/bin
copying bin/git-ime -> build/bdist.linux-x86_64/wheel/imediff-2.4.data/data/bin
running install_egg_info
running egg_info
creating src/imediff.egg-info
writing src/imediff.egg-info/PKG-INFO
writing dependency_links to src/imediff.egg-info/dependency_links.txt
writing entry points to src/imediff.egg-info/entry_points.txt
writing top-level names to src/imediff.egg-info/top_level.txt
writing manifest file 'src/imediff.egg-info/SOURCES.txt'
reading manifest file 'src/imediff.egg-info/SOURCES.txt'
writing manifest file 'src/imediff.egg-info/SOURCES.txt'
Copying src/imediff.egg-info to build/bdist.linux-x86_64/wheel/imediff-2.4.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
adding license file "AUTHORS" (matched pattern "AUTHORS*")
creating build/bdist.linux-x86_64/wheel/imediff-2.4.dist-info/WHEEL
creating 'dist/imediff-2.4-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'imediff/__init__.py'
adding 'imediff/__main__.py'
adding 'imediff/cli.py'
adding 'imediff/config.py'
adding 'imediff/diff2lib.py'
adding 'imediff/diff3lib.py'
adding 'imediff/tui.py'
adding 'imediff/utils.py'
adding 'imediff-2.4.data/data/bin/git-ime'
adding 'imediff-2.4.data/data/lib/git_core/mergetools/imediff'
adding 'imediff-2.4.data/data/share/man/man1/git-ime.1'
adding 'imediff-2.4.data/data/share/man/man1/imediff.1'
adding 'imediff-2.4.dist-info/AUTHORS'
adding 'imediff-2.4.dist-info/LICENSE'
adding 'imediff-2.4.dist-info/METADATA'
adding 'imediff-2.4.dist-info/WHEEL'
adding 'imediff-2.4.dist-info/entry_points.txt'
adding 'imediff-2.4.dist-info/top_level.txt'
adding 'imediff-2.4.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
```

**Comment by eyalroz** [comment]
None of these suggestions had any effect. The errors I get, which I listed above, seem to be internal to this repository somehow, not external - i.e. not a missing outside resource.

**Comment by osamuaoki** [comment]
One thing I noticed is Python version difference.  Mine is 3.9 and yours is 3.6.

I felt suspicious around error messages like `/usr/lib/python3.6/importlib/_bootstrap.py:219` 

I googled "Python 3.6 import error". 

- https://stackoverflow.com/questions/56394350/how-to-resolve-this-import-error-in-python-3-6
- https://stackoverflow.com/questions/65397489/python-importerror-on-python-3-6-3-7-3-8-but-not-on-3-9
- https://github.com/justinfx/pyRpc/issues/6

So you may need newer python.

Why don't you install some virtualenv with newer python like mine?

**Comment by eyalroz** [comment]
> Why don't you install some virtualenv with newer python like mine?

1. Because I had not been asked by anybody to do that...
2. Because I'm not a pythonista, I'm not fluent in setting up environments.
3. Because I have limited privileges on the machine and can't go too wild on it.
4. Because it's excessive. A basic tool like yours should not be so capricious. I would say that you should be able to run with any Python version for which the relevant modules are available; or - have the setup/build script download what it needs and run that.

**Comment by osamuaoki** [comment]
Yes, fair answers.  I am no expert on python either.  I don't know virtualenv well enough to test it easily.  Besides, monkey patching older-Python bug is a skill beyond me.  Let's think about easier solution. 

Since I updated build system in line with the recent tutorial, this may be the factor causing this trouble.  (It was working with older Python 3.)  I now made a new branch `alternative` which uses older setup.py style and have no i18n.  Can you pull this new alternative branch and test it in your environment.

* https://github.com/osamuaoki/imediff/tree/alternative

Please note this  program is my personal project.  My time and skill to support different environment is limited.

**Comment by eyalroz** [comment]
I understand. I'm sorry if I came off as overly angry or accusative. I'll try that other branch.

**Comment by osamuaoki** [comment]
Currently, setup.cfg states:

```
[options]
package_dir =
        = src
packages = find:
python_requires = >=3.9
setup_requires = setuptools >= 42
```
So, I consider build failure under python 3.6 is not an issue for this package.

I am closing this after re-titling this issue

**Comment by osamuaoki** [comment]
Re-titled.
